// src/components/records/RecordAlertsCard.tsx
"use client";

import React from "react";
import Link from "next/link";
import { TestRecord } from "@/lib/types/test.types";
import { AlertTriangle, ChevronRight } from "lucide-react";

interface RecordAlertsCardProps {
  testRecord: TestRecord;
}

export default function RecordAlertsCard({
  testRecord,
}: RecordAlertsCardProps) {
  if (!testRecord.alerts || testRecord.alerts.length === 0) return null;

  return (
    <div className="rounded-lg border bg-white shadow-sm overflow-hidden">
      <div className="px-5 py-3 border-b bg-amber-50 flex items-center gap-2">
        <AlertTriangle className="h-5 w-5 text-amber-600" />
        <div>
          <h3 className="text-base font-semibold text-amber-800">
            Triggered Alerts ({testRecord.alerts.length})
          </h3>
          <p className="text-sm text-amber-700 mt-0.5">
            Review and resolve the alerts generated by this test.
          </p>
        </div>
      </div>

      <ul className="divide-y divide-slate-100">
        {testRecord.alerts.map((alert) => (
          <li key={alert.id}>
            <Link
              href={`/dashboard/alerts/${alert.id}`}
              className="flex items-center justify-between px-4 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              <span className="font-mono text-slate-800">{alert.alert_id}</span>
              <ChevronRight className="h-4 w-4 text-slate-400" />
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
