// src/components/records/RecordAlertsCard.tsx
"use client";

import React from "react";
import Link from "next/link";
import { TestRecord } from "@/lib/types/test.types";
import { AlertTriangle, ChevronRight } from "lucide-react";

interface RecordAlertsCardProps {
  testRecord: TestRecord;
}

export default function RecordAlertsCard({ testRecord }: RecordAlertsCardProps) {
  // Don't render the card if there are no alerts
  if (!testRecord.alerts || testRecord.alerts.length === 0) {
    return null;
  }

  return (
    <div className="rounded-lg bg-white shadow-sm">
      <div className="p-4">
        <div className="flex items-center gap-2">
          <AlertTriangle className="h-5 w-5 text-amber-600" />
          <h3 className="text-lg font-semibold text-slate-900">
            Triggered Alerts ({testRecord.alerts.length})
          </h3>
        </div>
        <p className="text-sm text-slate-700 mt-1">
          Review and resolve the alerts generated by this test.
        </p>
      </div>
      <div className="p-2">
        <ul className="space-y-1">
          {testRecord.alerts.map((alert) => (
            <li key={alert.id}>
              <Link
                href={`/dashboard/alerts/${alert.id}`}
                className="flex items-center justify-between rounded-md p-2 text-sm font-medium text-slate-700 hover:bg-slate-100"
              >
                <span>{alert.alert_id}</span>
                <ChevronRight className="h-4 w-4 text-slate-500" />
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}